# Network dimensionality and universality of rules

## For every considered model, vary (1) number and (2) width of layers. Otherwise same as 'comparing'.

Created by Basile Van Hoorick, Fall 2020.

In [3]:
%run FF_common.ipynb

In [ ]:
def get_metrics(hyperparams, all_stats):

    num_configs = len(hyperparams)
    test_accs_up = []
    test_accs_down = []
    speeds_down = []

    for i in range(num_configs):

        universal, l, w, cap = hyperparams[i]
    #     print('Universal:', universal)
    #     print('Number hidden layers:', l)
    #     print('Hidden layer width:', w)
    #     print('Cap:', cap)

        stats_up, stats_down = all_stats[i]
        stats_up = convert_multi_stats_uncertainty(stats_up)
        stats_down = convert_multi_stats_uncertainty(stats_down)
        test_acc_up = stats_up[2][-1]
        test_acc_down = stats_down[2][-1]
        speed_down = np.mean(stats_down[2]) / test_acc_down

    #     print(f'Final upstream test accuracy: {test_acc_up*100:.2f}%')
    #     print(f'Final downstream test accuracy: {test_acc_down*100:.2f}%')
    #     print(f'Downstream speed of convergence: {speed_down*100:.2f}%')
    #     print()

        test_accs_up.append(test_acc_up)
        test_accs_down.append(test_acc_down)
        speeds_down.append(speed_down)

    test_accs_up = np.array(test_accs_up).reshape((2, 3, 3))
    test_accs_down = np.array(test_accs_down).reshape((2, 3, 3))
    speeds_down = np.array(speeds_down).reshape((2, 3, 3))
    metrics = np.multiply(test_accs_up, test_accs_down, speeds_down)

    print('Upstream accuracy:')
    print(test_accs_up)
    print('Downstream accuracy:')
    print(test_accs_down)
    print('Downstream speed:')
    print(speeds_down)
    print('Product:')
    print(metrics)

    return metrics

In [7]:
# IMPORTANT: Henceforth, we use GD directly on inputs but use plasticity rules in the output and hidden layers.
opts = Options(gd_input=True,
               use_graph_rule=True,
               gd_graph_rule=True,
               use_output_rule=True,
               gd_output_rule=True,
               gd_output=False)
scheme = UpdateScheme(cross_entropy_loss=True,
                      mse_loss=False,
                      update_misclassified_only=False,
                      update_all_edges=True)

# Feed-forward brain config.
n_up = 16  # Input layer size for meta-learning.
n_down = 16  # Input layer size for desired task training.
n = 16  # Input layer size.
m = 2  # Output layer size.
p = 0.5  # Connectivity probability.

# Training config.
num_runs = 5
num_rule_epochs = 50
num_epochs_upstream = 1
num_epochs_downstream = 1
dataset = 'relu'

## PrePost

In [ ]:
hyperparams = []
all_stats = []

for universal in [False, True]:  # Specialized rules or not?
    
    for l in [2, 3, 4]:  # Number of hidden layers.
        
        for w in [16, 32, 64]:  # Width of hidden layers.
            
            cap = w // 2  # Number of nodes firing per layer.
            print('Universal:', universal)
            print('Number hidden layers:', l)
            print('Hidden layer width:', w)
            print('Cap:', cap)
            hyperparams.append((universal, l, w, cap))
            
            brain_prepost_fact = lambda: FFLocalNet(
                n, m, l, w, p, cap,
                hl_rules=TableRule_PrePost() if universal else [TableRule_PrePost()] * (l-1),
                output_rule=TableRule_PrePost(), options=opts, update_scheme=scheme)
            
            print('==== Interpretation: Pre and Post ====')
            cur_stats = evaluate_brain(
                brain_prepost_fact, n, dataset=dataset,
                num_runs=num_runs, num_rule_epochs=num_rule_epochs,
                num_epochs_upstream=num_epochs_upstream, num_epochs_downstream=num_epochs_downstream)
            all_stats.append(cur_stats)

../DataGenerator.py:34: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  out2 = F.softmax(torch.matmul(out1, w1))
  0%|          | 0/50 [00:00<?, ?it/s]

Universal: False
Number hidden layers: 2
Hidden layer width: 16
Cap: 8
==== Interpretation: Pre and Post ====

Run 1 / 5...
Count of 0: 3601  Count of 1: 2399
Meta-learning...


  3%|▎         | 48/1500 [00:00<00:03, 476.22it/s]

Last loss: 0.4477
Last train accuracy: 0.8513
Last test accuracy: 0.8507
Count of 0: 3868  Count of 1: 2132
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.3540
INITIAL test accuracy: 0.3558
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6851
Last train accuracy: 0.6653
Last test accuracy: 0.6600


Run 2 / 5...
Count of 0: 3338  Count of 1: 2662
Meta-learning...


  3%|▎         | 48/1500 [00:00<00:03, 479.50it/s]

Last loss: 0.4409
Last train accuracy: 0.8707
Last test accuracy: 0.8382
Count of 0: 1543  Count of 1: 4457
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2560
INITIAL test accuracy: 0.2576
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5913
Last train accuracy: 0.7260
Last test accuracy: 0.7213


Run 3 / 5...
Count of 0: 4038  Count of 1: 1962
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.5178
Last train accuracy: 0.6827
Last test accuracy: 0.6698
Count of 0: 3400  Count of 1: 2600
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.4540
INITIAL test accuracy: 0.4524
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7560
Last train accuracy: 0.5673
Last test accuracy: 0.5664


Run 4 / 5...
Count of 0: 3174  Count of 1: 2826
Meta-learning...


  2%|▏         | 30/1500 [00:00<00:05, 292.61it/s]

Last loss: 0.4455
Last train accuracy: 0.8773
Last test accuracy: 0.8236
Count of 0: 4828  Count of 1: 1172
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.1860
INITIAL test accuracy: 0.1984
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.4931
Last train accuracy: 0.7980
Last test accuracy: 0.7856


Run 5 / 5...
Count of 0: 1835  Count of 1: 4165
Meta-learning...


  3%|▎         | 49/1500 [00:00<00:03, 481.90it/s]

Last loss: 0.4954
Last train accuracy: 0.7007
Last test accuracy: 0.7029
Count of 0: 3105  Count of 1: 2895
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.4987
INITIAL test accuracy: 0.5238
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7370
Last train accuracy: 0.5060
Last test accuracy: 0.5331

Universal: False
Number hidden layers: 2
Hidden layer width: 32
Cap: 16
==== Interpretation: Pre and Post ====

Run 1 / 5...
Count of 0: 1009  Count of 1: 4991
Meta-learning...


  3%|▎         | 47/1500 [00:00<00:03, 460.27it/s]

Last loss: 0.4212
Last train accuracy: 0.8407
Last test accuracy: 0.8427
Count of 0: 4296  Count of 1: 1704
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2653
INITIAL test accuracy: 0.2816
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5568
Last train accuracy: 0.7280
Last test accuracy: 0.7120


Run 2 / 5...
Count of 0: 5194  Count of 1: 806
Meta-learning...


  3%|▎         | 49/1500 [00:00<00:02, 485.60it/s]

Last loss: 0.6931
Last train accuracy: 0.8607
Last test accuracy: 0.8673
Count of 0: 2696  Count of 1: 3304
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.4533
INITIAL test accuracy: 0.4480
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.4533
Last test accuracy: 0.4480


Run 3 / 5...
Count of 0: 2791  Count of 1: 3209
Meta-learning...


  3%|▎         | 46/1500 [00:00<00:03, 455.95it/s]

Last loss: 0.4178
Last train accuracy: 0.8973
Last test accuracy: 0.8576
Count of 0: 4772  Count of 1: 1228
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2060
INITIAL test accuracy: 0.2042
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5499
Last train accuracy: 0.7587
Last test accuracy: 0.7498


Run 4 / 5...
Count of 0: 1691  Count of 1: 4309
Meta-learning...


  3%|▎         | 47/1500 [00:00<00:03, 460.64it/s]

Last loss: 0.3989
Last train accuracy: 0.8993
Last test accuracy: 0.8733
Count of 0: 4616  Count of 1: 1384
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2307
INITIAL test accuracy: 0.2307
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5353
Last train accuracy: 0.7947
Last test accuracy: 0.7802


Run 5 / 5...
Count of 0: 4293  Count of 1: 1707
Meta-learning...


  2%|▏         | 26/1500 [00:00<00:06, 219.22it/s]

Last loss: 0.4965
Last train accuracy: 0.7120
Last test accuracy: 0.7167
Count of 0: 1379  Count of 1: 4621
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2153
INITIAL test accuracy: 0.2347
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5356
Last train accuracy: 0.7880
Last test accuracy: 0.7647

Universal: False
Number hidden layers: 2
Hidden layer width: 64
Cap: 32
==== Interpretation: Pre and Post ====

Run 1 / 5...
Count of 0: 2658  Count of 1: 3342
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6931
Last train accuracy: 0.4320
Last test accuracy: 0.4467
Count of 0: 33  Count of 1: 5967
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.0040
INITIAL test accuracy: 0.0060
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.0040
Last test accuracy: 0.0060


Run 2 / 5...
Count of 0: 2876  Count of 1: 3124
Meta-learning...


  3%|▎         | 42/1500 [00:00<00:03, 415.84it/s]

Last loss: 0.6931
Last train accuracy: 0.4740
Last test accuracy: 0.4811
Count of 0: 4089  Count of 1: 1911
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.6787
INITIAL test accuracy: 0.6824
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.6787
Last test accuracy: 0.6824


Run 3 / 5...
Count of 0: 5320  Count of 1: 680
Meta-learning...


  3%|▎         | 42/1500 [00:00<00:03, 415.39it/s]

Last loss: 0.3856
Last train accuracy: 0.8973
Last test accuracy: 0.8831
Count of 0: 5410  Count of 1: 590
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.9167
INITIAL test accuracy: 0.8967
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.3940
Last train accuracy: 0.9167
Last test accuracy: 0.8967


Run 4 / 5...
Count of 0: 3719  Count of 1: 2281
Meta-learning...


  3%|▎         | 50/1500 [00:00<00:02, 497.53it/s]

Last loss: 0.3941
Last train accuracy: 0.9173
Last test accuracy: 0.8767
Count of 0: 1338  Count of 1: 4662
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2160
INITIAL test accuracy: 0.2253
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5045
Last train accuracy: 0.7907
Last test accuracy: 0.7793


Run 5 / 5...
Count of 0: 1167  Count of 1: 4833
Meta-learning...


  2%|▏         | 26/1500 [00:00<00:05, 254.86it/s]

Last loss: 0.4487
Last train accuracy: 0.8127
Last test accuracy: 0.8076
Count of 0: 1539  Count of 1: 4461
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2507
INITIAL test accuracy: 0.2584
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5874
Last train accuracy: 0.7453
Last test accuracy: 0.7402

Universal: False
Number hidden layers: 3
Hidden layer width: 16
Cap: 8
==== Interpretation: Pre and Post ====

Run 1 / 5...
Count of 0: 4612  Count of 1: 1388
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6931
Last train accuracy: 0.7553
Last test accuracy: 0.7731
Count of 0: 4283  Count of 1: 1717
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.7187
INITIAL test accuracy: 0.7122
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.7187
Last test accuracy: 0.7122


Run 2 / 5...
Count of 0: 4239  Count of 1: 1761
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.4865
Last train accuracy: 0.7233
Last test accuracy: 0.7009
Count of 0: 5191  Count of 1: 809
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.1433
INITIAL test accuracy: 0.1518
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.4380
Last train accuracy: 0.8680
Last test accuracy: 0.8642


Run 3 / 5...
Count of 0: 2526  Count of 1: 3474
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.4526
Last train accuracy: 0.8487
Last test accuracy: 0.8273
Count of 0: 3775  Count of 1: 2225
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.6280
INITIAL test accuracy: 0.6296
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7422
Last train accuracy: 0.5653
Last test accuracy: 0.5782


Run 4 / 5...
Count of 0: 2668  Count of 1: 3332
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.4098
Last train accuracy: 0.8840
Last test accuracy: 0.8698
Count of 0: 1597  Count of 1: 4403
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2713
INITIAL test accuracy: 0.2644
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5833
Last train accuracy: 0.7307
Last test accuracy: 0.7360


Run 5 / 5...
Count of 0: 3069  Count of 1: 2931
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.4404
Last train accuracy: 0.8720
Last test accuracy: 0.8356
Count of 0: 1915  Count of 1: 4085
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.3407
INITIAL test accuracy: 0.3120
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6013
Last train accuracy: 0.6893
Last test accuracy: 0.6800

Universal: False
Number hidden layers: 3
Hidden layer width: 32
Cap: 16
==== Interpretation: Pre and Post ====

Run 1 / 5...
Count of 0: 3934  Count of 1: 2066
Meta-learning...


  3%|▎         | 43/1500 [00:00<00:03, 424.26it/s]

Last loss: 0.5179
Last train accuracy: 0.6660
Last test accuracy: 0.6522
Count of 0: 2095  Count of 1: 3905
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.6407
INITIAL test accuracy: 0.6351
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6428
Last train accuracy: 0.6500
Last test accuracy: 0.6489


Run 2 / 5...
Count of 0: 5441  Count of 1: 559
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.3848
Last train accuracy: 0.9007
Last test accuracy: 0.9089
Count of 0: 3326  Count of 1: 2674
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.5687
INITIAL test accuracy: 0.5496
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7348
Last train accuracy: 0.5687
Last test accuracy: 0.5496


Run 3 / 5...
Count of 0: 2273  Count of 1: 3727
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6931
Last train accuracy: 0.3847
Last test accuracy: 0.3769
Count of 0: 3299  Count of 1: 2701
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.5407
INITIAL test accuracy: 0.5529
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.5407
Last test accuracy: 0.5529


Run 4 / 5...
Count of 0: 2829  Count of 1: 3171
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6931
Last train accuracy: 0.4527
Last test accuracy: 0.4778
Count of 0: 1039  Count of 1: 4961
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.1560
INITIAL test accuracy: 0.1789
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.1560
Last test accuracy: 0.1789


Run 5 / 5...
Count of 0: 4551  Count of 1: 1449
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6931
Last train accuracy: 0.7547
Last test accuracy: 0.7598
Count of 0: 778  Count of 1: 5222
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.1407
INITIAL test accuracy: 0.1260
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.1407
Last test accuracy: 0.1260

Universal: False
Number hidden layers: 3
Hidden layer width: 64
Cap: 32
==== Interpretation: Pre and Post ====

Run 1 / 5...
Count of 0: 740  Count of 1: 5260
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.3937
Last train accuracy: 0.8933
Last test accuracy: 0.8724
Count of 0: 1351  Count of 1: 4649
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2087
INITIAL test accuracy: 0.2307
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5360
Last train accuracy: 0.7913
Last test accuracy: 0.7689


Run 2 / 5...
Count of 0: 4255  Count of 1: 1745
Meta-learning...


  2%|▏         | 31/1500 [00:00<00:04, 306.70it/s]

Last loss: 0.4856
Last train accuracy: 0.7013
Last test accuracy: 0.7118
Count of 0: 3404  Count of 1: 2596
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.5613
INITIAL test accuracy: 0.5693
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7486
Last train accuracy: 0.5613
Last test accuracy: 0.5693


Run 3 / 5...
Count of 0: 5499  Count of 1: 501
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6931
Last train accuracy: 0.9093
Last test accuracy: 0.9189
Count of 0: 4188  Count of 1: 1812
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.6907
INITIAL test accuracy: 0.7004
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.6907
Last test accuracy: 0.7004


Run 4 / 5...
Count of 0: 976  Count of 1: 5024
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6931
Last train accuracy: 0.1607
Last test accuracy: 0.1633
Count of 0: 3548  Count of 1: 2452
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.5927
INITIAL test accuracy: 0.5909
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.5927
Last test accuracy: 0.5909


Run 5 / 5...
Count of 0: 3229  Count of 1: 2771
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6931
Last train accuracy: 0.5573
Last test accuracy: 0.5318
Count of 0: 3786  Count of 1: 2214
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.6340
INITIAL test accuracy: 0.6300
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.6340
Last test accuracy: 0.6300

Universal: False
Number hidden layers: 4
Hidden layer width: 16
Cap: 8
==== Interpretation: Pre and Post ====

Run 1 / 5...
Count of 0: 2948  Count of 1: 3052
Meta-learning...


  2%|▏         | 28/1500 [00:00<00:05, 277.31it/s]

Last loss: 0.6912
Last train accuracy: 0.4967
Last test accuracy: 0.4896
Count of 0: 2990  Count of 1: 3010
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.4827
INITIAL test accuracy: 0.5036
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.4827
Last test accuracy: 0.5036


Run 2 / 5...
Count of 0: 2713  Count of 1: 3287
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6931
Last train accuracy: 0.4453
Last test accuracy: 0.4544
Count of 0: 1900  Count of 1: 4100
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.3100
INITIAL test accuracy: 0.3189
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.3100
Last test accuracy: 0.3189


Run 3 / 5...
Count of 0: 3655  Count of 1: 2345
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6931
Last train accuracy: 0.6000
Last test accuracy: 0.6122
Count of 0: 3889  Count of 1: 2111
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.6413
INITIAL test accuracy: 0.6504
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.6413
Last test accuracy: 0.6504


Run 4 / 5...
Count of 0: 3662  Count of 1: 2338
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6931
Last train accuracy: 0.6153
Last test accuracy: 0.6087
Count of 0: 3035  Count of 1: 2965
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.5060
INITIAL test accuracy: 0.5058
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.5060
Last test accuracy: 0.5058


Run 5 / 5...
Count of 0: 4714  Count of 1: 1286
Meta-learning...


  1%|          | 15/1500 [00:00<00:09, 149.95it/s]

Last loss: 0.6931
Last train accuracy: 0.7913
Last test accuracy: 0.7838
Count of 0: 971  Count of 1: 5029
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.1740
INITIAL test accuracy: 0.1578
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.1740
Last test accuracy: 0.1578

Universal: False
Number hidden layers: 4
Hidden layer width: 32
Cap: 16
==== Interpretation: Pre and Post ====

Run 1 / 5...
Count of 0: 5179  Count of 1: 821
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.4033
Last train accuracy: 0.8600
Last test accuracy: 0.8642
Count of 0: 3357  Count of 1: 2643
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.4253
INITIAL test accuracy: 0.4396
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7738
Last train accuracy: 0.5700
Last test accuracy: 0.5560


Run 2 / 5...
Count of 0: 2172  Count of 1: 3828
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.5659
Last train accuracy: 0.6380
Last test accuracy: 0.6478
Count of 0: 6000  Count of 1: 0
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 1.0000
INITIAL test accuracy: 1.0000
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 1.0000
Last test accuracy: 1.0000


Run 3 / 5...
Count of 0: 5941  Count of 1: 59
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.3241
Last train accuracy: 0.9893
Last test accuracy: 0.9904
Count of 0: 1769  Count of 1: 4231
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.7120
INITIAL test accuracy: 0.7027
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6333
Last train accuracy: 0.7127
Last test accuracy: 0.7027


Run 4 / 5...
Count of 0: 4823  Count of 1: 1177
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6445
Last train accuracy: 0.8060
Last test accuracy: 0.8031
Count of 0: 5789  Count of 1: 211
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.9600
INITIAL test accuracy: 0.9664
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.3588
Last train accuracy: 0.9600
Last test accuracy: 0.9664


Run 5 / 5...
Count of 0: 5274  Count of 1: 726
Meta-learning...


  2%|▏         | 27/1500 [00:00<00:05, 269.96it/s]

Last loss: 0.3998
Last train accuracy: 0.8713
Last test accuracy: 0.8816
Count of 0: 4383  Count of 1: 1617
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.7360
INITIAL test accuracy: 0.7287
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5591
Last train accuracy: 0.7360
Last test accuracy: 0.7287

Universal: False
Number hidden layers: 4
Hidden layer width: 64
Cap: 32
==== Interpretation: Pre and Post ====

Run 1 / 5...
Count of 0: 1057  Count of 1: 4943
Meta-learning...


 78%|███████▊  | 39/50 [02:52<00:48,  4.41s/it]

In [41]:
metrics_prepost = get_metrics(hyperparams_prepost, all_stats_prepost)

Upstream accuracy:
[[[0.7965 0.842  0.7067]
  [0.8167 0.6317 0.6444]
  [0.5897 0.8329 0.5356]]

 [[0.7553 0.8688 0.9225]
  [0.6796 0.7672 0.6177]
  [0.6493 0.6701 0.6564]]]
Downstream accuracy:
[[[0.6525 0.7045 0.6271]
  [0.7144 0.4112 0.654 ]
  [0.4228 0.7957 0.5444]]

 [[0.6033 0.7105 0.7515]
  [0.5811 0.7759 0.5424]
  [0.5217 0.4597 0.4817]]]
Downstream speed:
[[[0.5198 0.5932 0.4431]
  [0.5834 0.2598 0.4214]
  [0.2493 0.6628 0.2916]]

 [[0.4557 0.6173 0.6933]
  [0.3949 0.5952 0.3351]
  [0.3388 0.3081 0.3162]]]
Product:
[[[0.5198 0.5932 0.4431]
  [0.5834 0.2598 0.4214]
  [0.2493 0.6628 0.2916]]

 [[0.4557 0.6173 0.6933]
  [0.3949 0.5952 0.3351]
  [0.3388 0.3081 0.3162]]]


Three best configs:

* Universal, 2 layers, 64 width (metric 0.69)

* Non-universal, 4 layers, 32 width (metric 0.66)

* Universal, 2 layers, 32 width (metric 0.62)

## PrePostCount

In [ ]:
hyperparams_prepostcount = []
all_stats_prepostcount = []

for universal in [False, True]:  # Specialized rules or not?
    
    for l in [2, 3, 4]:  # Number of hidden layers.
        
        for w in [16, 32, 64]:  # Width of hidden layers.
            
            cap = w // 2  # Number of nodes firing per layer.
            print('Universal:', universal)
            print('Number hidden layers:', l)
            print('Hidden layer width:', w)
            print('Cap:', cap)
            hyperparams_prepostcount.append((universal, l, w, cap))
            
            brain_prepostcount_fact = lambda: FFLocalNet(
                n, m, l, w, p, cap,
                hl_rules=TableRule_PrePostCount() if universal else [TableRule_PrePostCount()] * (l-1),
                output_rule=TableRule_PrePostCount(), options=opts, update_scheme=scheme)
            
            print('==== Interpretation: PrePostCount ====')
            cur_stats = evaluate_brain(
                brain_prepostcount_fact, n, dataset=dataset,
                num_runs=num_runs, num_rule_epochs=num_rule_epochs,
                num_epochs_upstream=num_epochs_upstream, num_epochs_downstream=num_epochs_downstream)
            all_stats_prepostcount.append(cur_stats)

  0%|          | 0/50 [00:00<?, ?it/s]

Universal: False
Number hidden layers: 2
Hidden layer width: 16
Cap: 8
==== Interpretation: PrePostCount ====

Run 1 / 5...
Count of 0: 150  Count of 1: 5850
Meta-learning...


  3%|▎         | 45/1500 [00:00<00:03, 444.57it/s]

Last loss: 0.3387
Last train accuracy: 0.9767
Last test accuracy: 0.9744
Count of 0: 2779  Count of 1: 3221
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.5273
INITIAL test accuracy: 0.5400
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7933
Last train accuracy: 0.5273
Last test accuracy: 0.5400


Run 2 / 5...
Count of 0: 2990  Count of 1: 3010
Meta-learning...


  3%|▎         | 47/1500 [00:00<00:03, 464.10it/s]

Last loss: 0.4394
Last train accuracy: 0.9020
Last test accuracy: 0.8824
Count of 0: 4021  Count of 1: 1979
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.6520
INITIAL test accuracy: 0.6762
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6622
Last train accuracy: 0.6460
Last test accuracy: 0.6704


Run 3 / 5...
Count of 0: 2585  Count of 1: 3415
Meta-learning...


  4%|▍         | 58/1500 [00:00<00:02, 577.01it/s]

Last loss: 0.6931
Last train accuracy: 0.4373
Last test accuracy: 0.4287
Count of 0: 1882  Count of 1: 4118
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.3213
INITIAL test accuracy: 0.3111
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6931
Last train accuracy: 0.3213
Last test accuracy: 0.3111


Run 4 / 5...
Count of 0: 1760  Count of 1: 4240
Meta-learning...


  3%|▎         | 45/1500 [00:00<00:03, 441.39it/s]

Last loss: 0.4936
Last train accuracy: 0.7533
Last test accuracy: 0.7509
Count of 0: 3124  Count of 1: 2876
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.4873
INITIAL test accuracy: 0.4847
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7910
Last train accuracy: 0.5187
Last test accuracy: 0.5204


Run 5 / 5...
Count of 0: 4171  Count of 1: 1829
Meta-learning...


  3%|▎         | 44/1500 [00:00<00:03, 439.76it/s]

Last loss: 0.5214
Last train accuracy: 0.6727
Last test accuracy: 0.7027
Count of 0: 5306  Count of 1: 694
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.1033
INITIAL test accuracy: 0.1233
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.4019
Last train accuracy: 0.8973
Last test accuracy: 0.8800

Universal: False
Number hidden layers: 2
Hidden layer width: 32
Cap: 16
==== Interpretation: PrePostCount ====

Run 1 / 5...
Count of 0: 1229  Count of 1: 4771
Meta-learning...


  4%|▎         | 54/1500 [00:00<00:02, 538.85it/s]

Last loss: 0.4393
Last train accuracy: 0.8160
Last test accuracy: 0.7991
Count of 0: 29  Count of 1: 5971
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.9880
INITIAL test accuracy: 0.9869
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.3222
Last train accuracy: 0.9880
Last test accuracy: 0.9869


Run 2 / 5...
Count of 0: 4376  Count of 1: 1624
Meta-learning...


  3%|▎         | 43/1500 [00:00<00:03, 423.69it/s]

Last loss: 0.4783
Last train accuracy: 0.7313
Last test accuracy: 0.7287
Count of 0: 2002  Count of 1: 3998
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.6567
INITIAL test accuracy: 0.6584
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6793
Last train accuracy: 0.6567
Last test accuracy: 0.6584


Run 3 / 5...
Count of 0: 2717  Count of 1: 3283
Meta-learning...


  4%|▎         | 54/1500 [00:00<00:02, 533.89it/s]

Last loss: 0.4296
Last train accuracy: 0.8867
Last test accuracy: 0.8642
Count of 0: 3720  Count of 1: 2280
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.6173
INITIAL test accuracy: 0.6209
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6413
Last train accuracy: 0.6653
Last test accuracy: 0.6838


Run 4 / 5...
Count of 0: 2282  Count of 1: 3718
Meta-learning...


  3%|▎         | 43/1500 [00:00<00:03, 421.30it/s]

Last loss: 0.5469
Last train accuracy: 0.5980
Last test accuracy: 0.6324
Count of 0: 3232  Count of 1: 2768
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.4533
INITIAL test accuracy: 0.4598
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7433
Last train accuracy: 0.5440
Last test accuracy: 0.5369


Run 5 / 5...
Count of 0: 5370  Count of 1: 630
Meta-learning...


  4%|▎         | 54/1500 [00:00<00:02, 532.23it/s]

Last loss: 0.3906
Last train accuracy: 0.8960
Last test accuracy: 0.8947
Count of 0: 2652  Count of 1: 3348
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.4420
INITIAL test accuracy: 0.4420
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7573
Last train accuracy: 0.5580
Last test accuracy: 0.5591

Universal: False
Number hidden layers: 2
Hidden layer width: 64
Cap: 32
==== Interpretation: PrePostCount ====

Run 1 / 5...
Count of 0: 3853  Count of 1: 2147
Meta-learning...


  3%|▎         | 39/1500 [00:00<00:03, 383.41it/s]

Last loss: 0.3943
Last train accuracy: 0.9220
Last test accuracy: 0.8938
Count of 0: 776  Count of 1: 5224
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.8633
INITIAL test accuracy: 0.8731
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.4750
Last train accuracy: 0.8460
Last test accuracy: 0.8582


Run 2 / 5...
Count of 0: 3124  Count of 1: 2876
Meta-learning...


  3%|▎         | 39/1500 [00:00<00:03, 388.63it/s]

Last loss: 0.4133
Last train accuracy: 0.9180
Last test accuracy: 0.8793
Count of 0: 3486  Count of 1: 2514
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.5967
INITIAL test accuracy: 0.5758
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5676
Last train accuracy: 0.7200
Last test accuracy: 0.6898


Run 3 / 5...
Count of 0: 4416  Count of 1: 1584
Meta-learning...


  3%|▎         | 39/1500 [00:00<00:03, 384.15it/s]

Last loss: 0.4927
Last train accuracy: 0.7327
Last test accuracy: 0.7371
Count of 0: 2185  Count of 1: 3815
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.3660
INITIAL test accuracy: 0.3636
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6846
Last train accuracy: 0.6307
Last test accuracy: 0.6367


Run 4 / 5...
Count of 0: 4155  Count of 1: 1845
Meta-learning...


  3%|▎         | 39/1500 [00:00<00:03, 386.10it/s]

Last loss: 0.4025
Last train accuracy: 0.8380
Last test accuracy: 0.8209
Count of 0: 4885  Count of 1: 1115
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2053
INITIAL test accuracy: 0.1793
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5033
Last train accuracy: 0.7960
Last test accuracy: 0.8213


Run 5 / 5...
Count of 0: 2035  Count of 1: 3965
Meta-learning...


  3%|▎         | 39/1500 [00:00<00:03, 387.16it/s]

Last loss: 0.5310
Last train accuracy: 0.6693
Last test accuracy: 0.6624
Count of 0: 1083  Count of 1: 4917
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.8213
INITIAL test accuracy: 0.8142
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5057
Last train accuracy: 0.8213
Last test accuracy: 0.8142

Universal: False
Number hidden layers: 3
Hidden layer width: 16
Cap: 8
==== Interpretation: PrePostCount ====

Run 1 / 5...
Count of 0: 3675  Count of 1: 2325
Meta-learning...


  3%|▎         | 42/1500 [00:00<00:03, 413.97it/s]

Last loss: 0.5407
Last train accuracy: 0.6313
Last test accuracy: 0.6062
Count of 0: 2552  Count of 1: 3448
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.5620
INITIAL test accuracy: 0.5767
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7830
Last train accuracy: 0.5620
Last test accuracy: 0.5767


Run 2 / 5...
Count of 0: 5274  Count of 1: 726
Meta-learning...


  3%|▎         | 42/1500 [00:00<00:03, 410.84it/s]

Last loss: 0.4043
Last train accuracy: 0.8727
Last test accuracy: 0.8811
Count of 0: 369  Count of 1: 5631
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.9360
INITIAL test accuracy: 0.9316
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.3723
Last train accuracy: 0.9360
Last test accuracy: 0.9316


Run 3 / 5...
Count of 0: 1258  Count of 1: 4742
Meta-learning...


  2%|▏         | 33/1500 [00:00<00:04, 329.50it/s]

Last loss: 0.4583
Last train accuracy: 0.8373
Last test accuracy: 0.8229
Count of 0: 2479  Count of 1: 3521
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.5987
INITIAL test accuracy: 0.5729
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6859
Last train accuracy: 0.5987
Last test accuracy: 0.5729


Run 4 / 5...
Count of 0: 1815  Count of 1: 4185
Meta-learning...


  2%|▏         | 33/1500 [00:00<00:04, 327.95it/s]

Last loss: 0.5079
Last train accuracy: 0.7133
Last test accuracy: 0.7231
Count of 0: 4347  Count of 1: 1653
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2913
INITIAL test accuracy: 0.2758
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6095
Last train accuracy: 0.7073
Last test accuracy: 0.7302


Run 5 / 5...
Count of 0: 2353  Count of 1: 3647
Meta-learning...


  2%|▏         | 33/1500 [00:00<00:04, 327.17it/s]

Last loss: 0.5498
Last train accuracy: 0.6413
Last test accuracy: 0.6238
Count of 0: 3250  Count of 1: 2750
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.5120
INITIAL test accuracy: 0.5516
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7744
Last train accuracy: 0.5120
Last test accuracy: 0.5516

Universal: False
Number hidden layers: 3
Hidden layer width: 32
Cap: 16
==== Interpretation: PrePostCount ====

Run 1 / 5...
Count of 0: 3803  Count of 1: 2197
Meta-learning...


  2%|▏         | 32/1500 [00:00<00:04, 311.38it/s]

Last loss: 0.5269
Last train accuracy: 0.6480
Last test accuracy: 0.6291
Count of 0: 4665  Count of 1: 1335
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2500
INITIAL test accuracy: 0.2142
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5328
Last train accuracy: 0.7513
Last test accuracy: 0.7862


Run 2 / 5...
Count of 0: 2902  Count of 1: 3098
Meta-learning...


  2%|▏         | 32/1500 [00:00<00:04, 318.28it/s]

Last loss: 0.6638
Last train accuracy: 0.5340
Last test accuracy: 0.5253
Count of 0: 4554  Count of 1: 1446
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2433
INITIAL test accuracy: 0.2436
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5348
Last train accuracy: 0.7573
Last test accuracy: 0.7596


Run 3 / 5...
Count of 0: 1806  Count of 1: 4194
Meta-learning...


  2%|▏         | 32/1500 [00:00<00:04, 318.03it/s]

Last loss: 0.5066
Last train accuracy: 0.6920
Last test accuracy: 0.7127
Count of 0: 862  Count of 1: 5138
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.8467
INITIAL test accuracy: 0.8287
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.4330
Last train accuracy: 0.8633
Last test accuracy: 0.8482


Run 4 / 5...
Count of 0: 1836  Count of 1: 4164
Meta-learning...


  2%|▏         | 32/1500 [00:00<00:04, 317.09it/s]

Last loss: 0.5032
Last train accuracy: 0.6927
Last test accuracy: 0.6953
Count of 0: 4894  Count of 1: 1106
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.1887
INITIAL test accuracy: 0.1829
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5091
Last train accuracy: 0.8113
Last test accuracy: 0.8171


Run 5 / 5...
Count of 0: 5065  Count of 1: 935
Meta-learning...


  2%|▏         | 32/1500 [00:00<00:04, 316.19it/s]

Last loss: 0.4013
Last train accuracy: 0.8520
Last test accuracy: 0.8416
Count of 0: 3332  Count of 1: 2668
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.5640
INITIAL test accuracy: 0.5524
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7303
Last train accuracy: 0.5640
Last test accuracy: 0.5524

Universal: False
Number hidden layers: 3
Hidden layer width: 64
Cap: 32
==== Interpretation: PrePostCount ====

Run 1 / 5...
Count of 0: 1364  Count of 1: 4636
Meta-learning...


  2%|▏         | 26/1500 [00:00<00:05, 259.09it/s]

Last loss: 0.4794
Last train accuracy: 0.7747
Last test accuracy: 0.7764
Count of 0: 2199  Count of 1: 3801
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.3693
INITIAL test accuracy: 0.3656
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6876
Last train accuracy: 0.6287
Last test accuracy: 0.6333


Run 2 / 5...
Count of 0: 4038  Count of 1: 1962
Meta-learning...


  2%|▏         | 29/1500 [00:00<00:05, 280.28it/s]

Last loss: 0.5246
Last train accuracy: 0.6780
Last test accuracy: 0.6713
Count of 0: 4505  Count of 1: 1495
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2573
INITIAL test accuracy: 0.2482
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5615
Last train accuracy: 0.7420
Last test accuracy: 0.7538


Run 3 / 5...
Count of 0: 639  Count of 1: 5361
Meta-learning...


  2%|▏         | 29/1500 [00:00<00:05, 282.05it/s]

Last loss: 0.3776
Last train accuracy: 0.9080
Last test accuracy: 0.8924
Count of 0: 1768  Count of 1: 4232
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.6927
INITIAL test accuracy: 0.7087
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6140
Last train accuracy: 0.6927
Last test accuracy: 0.7087


Run 4 / 5...
Count of 0: 207  Count of 1: 5793
Meta-learning...


  2%|▏         | 29/1500 [00:00<00:05, 281.81it/s]

Last loss: 0.3391
Last train accuracy: 0.9700
Last test accuracy: 0.9647
Count of 0: 4314  Count of 1: 1686
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.2887
INITIAL test accuracy: 0.2789
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.5900
Last train accuracy: 0.7120
Last test accuracy: 0.7213


Run 5 / 5...
Count of 0: 530  Count of 1: 5470
Meta-learning...


  2%|▏         | 29/1500 [00:00<00:05, 281.92it/s]

Last loss: 0.3755
Last train accuracy: 0.9113
Last test accuracy: 0.9164
Count of 0: 1904  Count of 1: 4096
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.7000
INITIAL test accuracy: 0.6756
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6243
Last train accuracy: 0.7000
Last test accuracy: 0.6756

Universal: False
Number hidden layers: 4
Hidden layer width: 16
Cap: 8
==== Interpretation: PrePostCount ====

Run 1 / 5...
Count of 0: 2728  Count of 1: 3272
Meta-learning...


  0%|          | 0/1500 [00:00<?, ?it/s]

Last loss: 0.6088
Last train accuracy: 0.5907
Last test accuracy: 0.5973
Count of 0: 2047  Count of 1: 3953
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.3447
INITIAL test accuracy: 0.3400
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.6388
Last train accuracy: 0.6760
Last test accuracy: 0.6707


Run 2 / 5...
Count of 0: 707  Count of 1: 5293
Meta-learning...


  2%|▏         | 26/1500 [00:00<00:05, 251.82it/s]

Last loss: 0.3966
Last train accuracy: 0.8987
Last test accuracy: 0.8918
Count of 0: 2251  Count of 1: 3749
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.3773
INITIAL test accuracy: 0.3744
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7075
Last train accuracy: 0.6233
Last test accuracy: 0.6238


Run 3 / 5...
Count of 0: 1228  Count of 1: 4772
Meta-learning...


100%|██████████| 50/50 [04:00<00:00,  4.80s/it]


Last loss: 0.4604
Last train accuracy: 0.8300
Last test accuracy: 0.8216
Count of 0: 269  Count of 1: 5731
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.0380


  1%|          | 16/1500 [00:00<00:09, 157.75it/s]

INITIAL test accuracy: 0.0471
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.3749
Last train accuracy: 0.9293
Last test accuracy: 0.9216


Run 4 / 5...
Count of 0: 4049  Count of 1: 1951
Meta-learning...


  2%|▏         | 24/1500 [00:00<00:06, 238.26it/s]

Last loss: 0.5239
Last train accuracy: 0.6740
Last test accuracy: 0.6751
Count of 0: 3075  Count of 1: 2925
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.4880
INITIAL test accuracy: 0.5207
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.8039
Last train accuracy: 0.5113
Last test accuracy: 0.4889


Run 5 / 5...
Count of 0: 4708  Count of 1: 1292
Meta-learning...


100%|██████████| 50/50 [04:12<00:00,  5.05s/it]


Last loss: 0.4406
Last train accuracy: 0.7880
Last test accuracy: 0.7836
Count of 0: 3787  Count of 1: 2213
Training SAME brain instance (NO backprop)...
===> WARNING: Backprop is disabled, which means that all layers without rules will never change their weights!
===> This is NOT recommended by Basile!
INITIAL train accuracy: 0.3967


  2%|▏         | 26/1500 [00:00<00:05, 249.73it/s]

INITIAL test accuracy: 0.3622
Epoch 1 / 1 ...


  0%|          | 0/50 [00:00<?, ?it/s]


Last loss: 0.7174
Last train accuracy: 0.6053
Last test accuracy: 0.6398

Universal: False
Number hidden layers: 4
Hidden layer width: 32
Cap: 16
==== Interpretation: PrePostCount ====

Run 1 / 5...
Count of 0: 4987  Count of 1: 1013
Meta-learning...


 60%|██████    | 30/50 [02:47<01:45,  5.29s/it]

In [ ]:
metrics_prepostcount = get_metrics(hyperparams_prepostcount, all_stats_prepostcount)

## PrePostPercent

In [ ]:
hyperparams_prepostpercent = []
all_stats_prepostpercent = []

for universal in [False, True]:  # Specialized rules or not?
    
    for l in [2, 3, 4]:  # Number of hidden layers.
        
        for w in [16, 32, 64]:  # Width of hidden layers.
            
            cap = w // 2  # Number of nodes firing per layer.
            print('Universal:', universal)
            print('Number hidden layers:', l)
            print('Hidden layer width:', w)
            print('Cap:', cap)
            hyperparams_prepostpercent.append((universal, l, w, cap))
            
            brain_prepostpercent_fact = lambda: FFLocalNet(
                n, m, l, w, p, cap,
                hl_rules=TableRule_PrePostPercent() if universal else [TableRule_PrePostPercent()] * (l-1),
                output_rule=TableRule_PrePostPercent(), options=opts, update_scheme=scheme)
            
            print('==== Interpretation: PrePostPercent ====')
            cur_stats = evaluate_brain(
                brain_prepostpercent_fact, n, dataset=dataset,
                num_runs=num_runs, num_rule_epochs=num_rule_epochs,
                num_epochs_upstream=num_epochs_upstream, num_epochs_downstream=num_epochs_downstream)
            all_stats_prepostpercent.append(cur_stats)

In [ ]:
metrics_prepostpercent = get_metrics(hyperparams_prepostpercent, all_stats_prepostpercent)